### ISSUE TITLE
Darknet version?

### ISSUE THREAD

**Issue by lorenzobattelli** [chumingqian/Deploy_Yolov4_On_Ultra96_v2#2]
Hello there, 
which is the Darknet version , or release, that has been used for this tutorial?

Greetings

**Comment by chumingqian** [comment]
Hi, @lorenzobattelli :
     It's  yolov4, but also can  suit for  yolov3. But  before you getting started,  you need to modify the configuration file darknet/cfg/yolov4.cfg to be compatible with the Zynq Ultrascale+ DPU. The MISH activation layers are swapped to leaky as the DPU doesn't support MISH. The SPP module maxpool section has kernel sizes of 5, 9, 13, and the DPU only supports a maxpool kernel size of upto 8. There are also additional restrictions for maxpool when the stride=1 and converting to Caffe. There are 3 possible changes you can make to the SPP Section:

Change all max kernel sizes to 1, 1, 1
Change all kernel sizes 3,5, 7
Comment out max_pool layers
